name: GitHub Actions 定时任务 - 每晚定时爬取并保存到Ali cloud上

on:
  schedule:
    - cron: '0 18 * * 6' # 每天的 UTC 00:00 执行

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.9.0

      - name: Install dependencies
        run: yarn

      - name: Run script
        run: node zhuoyue-boyifu/index.js
